channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.1.2
- pip:
  - mlflow==2.13.2
  - argparse==1.4.0
  - cffi==1.16.0
  - click==8.1.7
  - cloudpickle==3.1.0
  - cytoolz==0.12.0
  - dask-expr==1.1.19
  - defusedxml==0.7.1
  - distributed==2023.6.0
  - graphviz==0.20.3
  - importlib-metadata==7.1.0
  - jinja2==3.1.2
  - lightgbm==4.4.0
  - lz4==4.3.2
  - matplotlib==3.7.2
  - mmh3==4.1.0
  - numpy==1.24.3
  - packaging==24.1
  - pandas==2.0.3
  - pathlib==1.0.1
  - pyarrow==15.0.2
  - python-snappy==0.6.1
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.11.1
  - setproctitle==1.3.3
  - uuid==1.30
  - xxhash==2.0.2
  - zstandard==0.19.0
name: mlflow-env
