channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.1.2
- pip:
  - mlflow==2.13.2
  - argparse==1.4.0
  - cloudpickle==3.1.0
  - lz4==4.3.2
  - numpy==1.24.3
  - packaging==24.1
  - pandas==2.0.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.11.1
  - uuid==1.30
  - xgboost==2.1.0
name: mlflow-env
